name: Calculator App Addition Test

on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'First number for addition'
        required: true
        default: '3'
      num2:
        description: 'Second number for addition'
        required: true
        default: '5'
      expectedResult:
        description: 'Expected result of the addition'
        required: true
        default: '8'

jobs:
  test:
    name: Run Appium Calculator Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      # 3. Install Appium and dependencies
      - name: Install Appium
        run: |
          npm install -g appium
          appium -v

      - name: Install UiAutomator2 Driver
        run: |
          appium driver install uiautomator2

      - name: Verify Drivers Installed
        run: |
          appium driver list

      # 4. Install Emulator Dependencies
      - name: Install Emulator Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils

      # 5. Download system image for Pixel 8 Pro API 35
      - name: Download System Image for Pixel 8 Pro API 35
        run: |
          echo y | sdkmanager "system-images;android-35;google_apis;x86_64"

      # 6. Create the Pixel 8 Pro AVD
      - name: Create Pixel 8 Pro AVD
        run: |
          echo no | avdmanager create avd -n Pixel_8_Pro_API_35 -k "system-images;android-35;google_apis;x86_64" --force

      # 7. Start the Emulator in headless mode
      - name: Start Emulator
        run: |
          emulator -avd Pixel_8_Pro_API_35 -no-window -no-boot-anim &
          adb wait-for-device

      # 8. Install Google Calculator APK on the Emulator
      - name: Install Google Calculator APK
        run: |
          adb install ./apk/calc.apk

      # 9. Start Appium Server in the background
      - name: Start Appium Server
        run: |
          nohup appium --address 127.0.0.1 --port 4723 &

      # 10. Install required dependencies
      - name: Install Dependencies
        run: |
          mvn clean install

      # 11. Run the test with manual inputs
      - name: Run Appium Test
        run: |
          mvn test -Dnum1=${{ github.event.inputs.num1 }} -Dnum2=${{ github.event.inputs.num2 }} -DexpectedResult=${{ github.event.inputs.expectedResult }}
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}

      # 12. Upload test results as artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: target/surefire-reports/  # Path for Maven test reports
