name: Calculator App Addition Test

on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'First number for addition'
        required: true
        default: '3'
      num2:
        description: 'Second number for addition'
        required: true
        default: '5'
      expectedResult:
        description: 'Expected result of the addition'
        required: true
        default: '8'

jobs:
  test:
    name: Run Appium Calculator Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Appium
        run: |
          npm install -g appium
          appium -v

      - name: Install UiAutomator2 driver
        run: |
          appium driver install uiautomator2

      - name: Install android emulator and system image
        run: |
          echo y | sdkmanager --sdk_root=$ANDROID_HOME "system-images;android-34;google_apis;x86_64"
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "emulator"

      - name: Create AVD with Android API 34
        run: |
          echo "no" | avdmanager create avd -n Android34 -k "system-images;android-34;google_apis;x86_64"

      - name: Start emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd Android34 -no-window -no-boot-anim -gpu off -accel off -no-snapshot-save &

      - name: Wait for emulator to up and running
        run: |
          adb devices
          while ! adb -s emulator-5554 wait-for-device; do
            echo "Waiting for device to be online..."
            sleep 5
          done
          while [[ $(adb shell getprop sys.boot_completed 2>/dev/null) != "1" ]]; do
            echo "Still waiting for emulator to boot..."
            sleep 5
          done
          echo "Emulator booted successfully."
          adb devices
          sleep 20

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Start Appium server
        run: |
          echo "Starting Appium server..."
          nohup appium --address 127.0.0.1 --port 4723 --log appium.log --log-level info &
          sleep 5
          echo "Appium server started."

      - name: Verify Appium server status
        run: |
          curl -X GET http://127.0.0.1:4723/status || {
            echo "Appium server is not running!"
            cat appium.log
            exit 1
          }

      - name: Install APKs on emulator
        run: |
          adb install -g ./apk/calc.apk
          adb install -g ./apk/appium_settings.apk

      - name: Run Appium test
        run: |
          mvn test -Dnum1=${{ github.event.inputs.num1 }} -Dnum2=${{ github.event.inputs.num2 }} -DexpectedResult=${{ github.event.inputs.expectedResult }}
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}

      - name: Generate Test Report
        if: always()
        run: |
          echo "Generating test report..."
          mvn surefire-report:report -DskipTests=true || true

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: target/site

      - name: Upload Page Source
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: page-source
          path: screenshots/page_source_failure.xml
