name: Calculator App Addition Test

on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'First number for addition'
        required: true
        default: '3'
      num2:
        description: 'Second number for addition'
        required: true
        default: '5'
      expectedResult:
        description: 'Expected result of the addition'
        required: true
        default: '8'

jobs:
  test:
    name: Run Appium Calculator Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      # 3. Set up Android tools
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # 4. Install Appium
      - name: Install Appium
        run: |
          npm install -g appium
          appium -v

      - name: Install UiAutomator2 Driver
        run: |
          appium driver install uiautomator2

      - name: Verify Drivers Installed
        run: |
          appium driver list

      # 5. Install Android Emulator and System Image
      - name: Install Android Emulator and System Image
        run: |
          echo y | sdkmanager --sdk_root=$ANDROID_HOME "system-images;android-35;google_apis;x86_64"
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "emulator"

      # 6. Create AVD (Pixel 8 Pro API 35)
      - name: Create Pixel 8 Pro AVD
        run: |
          echo "no" | avdmanager create avd -n Android35 -k "system-images;android-35;google_apis;x86_64"


      # 7. Start Emulator
      - name: Start Emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd Android35 -no-window -no-boot-anim -gpu off -accel off -no-snapshot-save &

      # Wait emulator for fully loaded
      - name: Wait for emulator to start
        run: |
          adb devices
          while ! adb -s emulator-5554 wait-for-device; do
            echo "Waiting for device to be online..."
            sleep 5
          done
          while [[ $(adb shell getprop sys.boot_completed 2>/dev/null) != "1" ]]; do
            echo "Still waiting for emulator to boot..."
            sleep 5
          done
          echo "Emulator booted. Waiting for package manager service to come online..."
          while ! adb shell 'pm list packages' > /dev/null 2>&1; do
            echo "Waiting for package manager service..."
            sleep 5
          done
          echo "Package manager is now available. Emulator is fully ready!"
          adb devices
          sleep 20

      # 8. Install required dependencies
      - name: Install Dependencies
        run: |
          mvn clean install -DskipTests

      - name: Verify APK Path
        run: |
          if [ -f "./apk/calc.apk" ]; then
            echo "APK found."
          else
            echo "APK not found!"
            exit 1
          fi

      - name: Install Google Calculator APK on Emulator
        run: |
          adb install ./apk/calc.apk

      - name: Start Appium Server
        run: |
          echo "Starting Appium server..."
          nohup appium --address 127.0.0.1 --port 4723 --log appium.log --log-level info &
          sleep 5
          echo "Appium server started."

      - name: Verify Appium Server Status
        run: |
          echo "Verifying Appium server is up..."
          curl -X GET http://127.0.0.1:4723/status || {
            echo "Appium server is not running!"
            cat appium.log
            exit 1
          }

      # 9. Run the test with manual inputs
      - name: Run Appium Test
        run: |
          mvn test -Dnum1=${{ github.event.inputs.num1 }} -Dnum2=${{ github.event.inputs.num2 }} -DexpectedResult=${{ github.event.inputs.expectedResult }}
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}

      # 10. Upload test results as artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: target/surefire-reports/  # Path for Maven test reports
